### ISSUE TITLE
Suggest passing in document.forms rather than document

### ISSUE THREAD

**Issue by jfmengels** [choonkeat/nativeform#1]
From what I can tell (but please tell me if this is incorrect), this library would work just as well if we passed in `documenf.forms` and removed the ["forms" field access](https://github.com/choonkeat/nativeform/blob/main/src/NativeForm.elm#L262).

I feel that this would be somewhat more secure, because if you pass in `document`, then decoders (not necessarily the ones in this packages) could be used to access any kind of data I think, even dynamic ones, which can lead to some impurities and therefore weird behavior.

It also feels a lot less scary to pass `document.forms` to a library I haven't audited than to pass `document`.

What do you think?

**Comment by choonkeat** [comment]
Good point! Shall change if it works 👌

**Comment by choonkeat** [comment]
It works 👍 https://github.com/choonkeat/nativeform/commit/ccd465b969866bbc3c1ef5793883f66e29e88a67

~I'm still experimenting on a [config api](https://github.com/choonkeat/nativeform/compare/build-helpers) and maybe cut a release after that?~ released https://github.com/choonkeat/nativeform/releases/tag/2.1.0
